temp_low="4000"   # Keeps it warm at night and early morning.
temp_high="6500"  # Daylight mode for work hours.
sunrise="08:00"   # Warmer colors until 8:00 (or 9:00 if you want).
sunset="19:00"    # Starts shifting to warm colors at 19:00.
longitude=24.02324000  # Your location in Lviv.
latitude=49.83826000   # Your location in Lviv.
duration="900"    # Smooth 15-minute transition.
